namespace <?php echo $module ?>\V<?php echo $version ?>\Rest\<?php echo $resource ?>;


class <?php echo $classname ?>
{
    /**
     * Export this entity to an array
     *
     * @return array
     */
    public function getArrayCopy()
    {

    }

    /**
     * Populate this entity with data from an array
     *
     * @return void
     */
    public function exchangeArray($input)
    {

    }
}
